import type { Database } from './database.types'

type SiteSettings = Database['public']['Tables']['site_settings']['Row']
type Event = Database['public']['Tables']['events']['Row']
type PortfolioItem = Database['public']['Tables']['portfolio_items']['Row']
type Testimonial = Database['public']['Tables']['testimonials']['Row']
type BlogPost = Database['public']['Tables']['blog_posts']['Row']
type SponsorshipInventory = Database['public']['Tables']['sponsorship_inventory']['Row']

export const placeholderSettings: SiteSettings = {
  id: '1',
  brand_name: 'Haven Productions',
  tagline: 'Where Sound Meets Vision',
  light_logo_url: '/logo.png',
  dark_logo_url: '/logo-dark.png',
  email: 'hello@havenproductions.com',
  phone: '+91 98765 43210',
  address: '12 Studio Lane, Bandra West',
  city: 'Mumbai',
  country: 'India',
  instagram_url: 'https://instagram.com/havenproductions',
  facebook_url: 'https://facebook.com/havenproductions',
  youtube_url: 'https://youtube.com/@havenproductions',
  twitter_url: 'https://twitter.com/havenprodn',
  linkedin_url: 'https://linkedin.com/company/havenproductions',
  whatsapp_number: '+919876543210',
  theme: 'modern',
  updated_at: new Date().toISOString(),
}

export const placeholderEvents: Event[] = [
  {
    id: '1',
    title: 'Neon Nights — Mumbai',
    slug: 'neon-nights-mumbai-2025',
    date: '2025-02-15T19:00:00',
    venue: 'Dome NSCI',
    city: 'Mumbai',
    vertical: 'events',
    status: 'upcoming',
    hero_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80',
    description: 'An electric night of indie music and brand activations, drawing 5,000+ music lovers.',
    expected_attendance: 5000,
    sponsorship_open: true,
    collab_open: true,
    sponsorship_spots_remaining: 3,
    featured: true,
    target_demo: 'Gen-Z / Millennials, Urban',
    media_gallery: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Rhythm & Roots Festival',
    slug: 'rhythm-roots-festival-2025',
    date: '2025-03-22T16:00:00',
    venue: 'Phoenix Palladium Grounds',
    city: 'Bangalore',
    vertical: 'music',
    status: 'upcoming',
    hero_image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80',
    description: 'A roots and world music celebration bringing together artists across genres.',
    expected_attendance: 8000,
    sponsorship_open: true,
    collab_open: false,
    sponsorship_spots_remaining: 5,
    featured: false,
    target_demo: 'Gen-Z / Millennials, Urban',
    media_gallery: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Haven Presents: Deep Focus',
    slug: 'deep-focus-audio-launch-2024',
    date: '2024-11-10T18:00:00',
    venue: 'Blue Frog',
    city: 'Mumbai',
    vertical: 'audio',
    status: 'past',
    hero_image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&q=80',
    description: 'A sold-out album launch event that garnered 2M+ streams in its first week.',
    expected_attendance: 600,
    sponsorship_open: false,
    collab_open: false,
    sponsorship_spots_remaining: 0,
    featured: false,
    target_demo: 'Gen-Z / Millennials, Urban',
    media_gallery: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const placeholderPortfolio: PortfolioItem[] = [
  {
    id: '1',
    title: 'Breakout EP — Arjun Mehta',
    vertical: 'music',
    client: 'Arjun Mehta',
    media_url: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=600&q=80',
    description: 'End-to-end EP production — writing, recording, mixing, mastering, and distribution.',
    metrics: '4.2M streams in 60 days, charted on Spotify India Viral 50',
    year: 2024,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'ReLaunch Ad Campaign — NovaBev',
    vertical: 'film',
    client: 'NovaBev Beverages',
    media_url: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80',
    description: '3-spot ad campaign produced in 12 days for a national product relaunch.',
    metrics: '120M impressions, 38% brand-recall lift in post-campaign survey',
    year: 2024,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Starfield Corporate Summit',
    vertical: 'events',
    client: 'Starfield Corp',
    media_url: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=600&q=80',
    description: 'Full-stack event production for a 1,200-delegate global leadership summit.',
    metrics: 'Zero incidents, 98% delegate satisfaction, delivered 2 days ahead of schedule',
    year: 2024,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'The Midnight Verse — Podcast',
    vertical: 'audio',
    client: 'Self-produced',
    media_url: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&q=80',
    description: 'Full production and global launch of a 12-episode storytelling podcast.',
    metrics: '#1 on Spotify India Podcasts, 800K downloads Season 1',
    year: 2023,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Apex Brand Activation — IPL Season',
    vertical: 'sponsorship',
    client: 'Apex Sports',
    media_url: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80',
    description: 'Title sponsorship placement across 4 major concert events during IPL season.',
    metrics: '12M+ reach, 3.2x ROI, 47K in-venue brand interactions',
    year: 2024,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Echoes Short Film',
    vertical: 'film',
    client: 'Independent',
    media_url: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&q=80',
    description: 'Award-winning 22-minute short film, festival circuit distribution.',
    metrics: 'Selected at 8 international festivals, Best Cinematography — CineAsia 2024',
    year: 2024,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Rise — Debut Album',
    vertical: 'music',
    client: 'Priya & the Collective',
    media_url: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&q=80',
    description: 'Full 10-track debut album production from scratch to streaming release.',
    metrics: '6.8M streams, featured on Apple Music New Music Daily',
    year: 2023,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'GlowFest Music Weekend',
    vertical: 'events',
    client: 'GlowFest Promoters',
    media_url: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=600&q=80',
    description: '2-day outdoor music festival, 18,000 total attendance.',
    metrics: '18K attendees, ₹4.2Cr gate revenue, 7 brand sponsors activated',
    year: 2023,
    featured: false,
    created_at: new Date().toISOString(),
  },
]

export const placeholderTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Arjun Mehta',
    role: 'Independent Artist',
    company: null,
    persona: 'artist',
    quote: 'Haven took my raw demos and turned them into something I\'m genuinely proud to release. 4M+ streams later, I can say they didn\'t just produce my music — they launched my career.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/men/32.jpg',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Priya Nair',
    role: 'Brand Marketing Lead',
    company: 'NovaBev Beverages',
    persona: 'brand',
    quote: 'We needed a production partner who understood brand ROI, not just creative flair. Haven delivered our entire 3-spot campaign in 12 days and it pulled a 38% brand-recall lift. That\'s accountable spend.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/women/44.jpg',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Rajan Verma',
    role: 'CMO',
    company: 'Apex Sports',
    persona: 'sponsor',
    quote: 'The sponsorship placement was seamless. Category exclusivity, real audience data, and a partnerships team that actually follows up with results. 3.2x ROI on our first activation.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/men/55.jpg',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Sunita Krishnan',
    role: 'Events Head',
    company: 'Starfield Corp',
    persona: 'events',
    quote: 'A 1,200-delegate summit with zero incidents. Haven handled permits, AV, catering coordination, and contingency — we just walked in as the host. Will never use another vendor.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/women/28.jpg',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Karan Singh',
    role: 'Line Producer',
    company: 'PixelBay Studios',
    persona: 'film',
    quote: 'End-to-end delivery on the ad campaign without a single call from me asking for status updates. That\'s the dream. Broadcast-grade output, on-budget, on-schedule.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/men/67.jpg',
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Meera Joshi',
    role: 'A&R Manager',
    company: 'Echo Records',
    persona: 'artist',
    quote: 'We sent three emerging artists to Haven this year. All three released on schedule, all three charted. That consistency is rare and it\'s why they\'re our default production house.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/women/72.jpg',
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Devraj Kumar',
    role: 'Event Promoter',
    company: 'GlowFest',
    persona: 'events',
    quote: '18,000 people over two days and we had more compliments on production quality than on the lineup itself. Haven made us look elite.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/men/81.jpg',
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Aisha Patel',
    role: 'Director',
    company: 'Independent',
    persona: 'film',
    quote: 'My short film got into 8 festivals. Haven\'s crew understood the creative vision and never compromised on it even when the schedule got tight. Real collaborators.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/women/19.jpg',
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Vikram Narayan',
    role: 'VP Marketing',
    company: 'ZenFit India',
    persona: 'sponsor',
    quote: 'The Neon Nights sponsorship gave us direct access to 5,000 of our exact target demographic. The ROI dashboard Haven sent post-event was detailed enough to justify a 3x bigger budget next season.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/men/43.jpg',
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Lakshmi Rao',
    role: 'Podcast Host',
    company: 'The Midnight Verse',
    persona: 'artist',
    quote: 'I came to Haven with a voice memo and a concept. They gave me a #1 podcast. The production quality, the launch strategy, the distribution setup — I couldn\'t have done it without them.',
    rating: 5,
    photo_url: 'https://randomuser.me/api/portraits/women/56.jpg',
    featured: false,
    created_at: new Date().toISOString(),
  },
]

export const placeholderBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'How to Take an Unsigned Artist from Studio to Streaming Charts in 45 Days',
    slug: 'unsigned-artist-studio-to-streaming-45-days',
    excerpt: 'The exact production sprint we\'ve run 23 times — and why timeline discipline is the biggest differentiator between a song that charts and one that disappears.',
    content: null,
    category: 'music',
    thumbnail_url: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=600&q=80',
    published: true,
    created_at: '2024-12-15T10:00:00',
    updated_at: '2024-12-15T10:00:00',
  },
  {
    id: '2',
    title: 'The Sponsorship Deck That Actually Converts: A Brand Marketer\'s Checklist',
    slug: 'sponsorship-deck-that-converts-brand-checklist',
    excerpt: 'Most sponsorship pitches fail before a brand even reads them. Here\'s what every marketing lead actually wants to see — and what you should cut.',
    content: null,
    category: 'sponsorship',
    thumbnail_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=80',
    published: true,
    created_at: '2024-12-08T10:00:00',
    updated_at: '2024-12-08T10:00:00',
  },
  {
    id: '3',
    title: '5 Things Every Event Production Contract Must Include (That Most Don\'t)',
    slug: 'event-production-contract-must-haves',
    excerpt: 'We\'ve produced 200+ events. These five clauses have saved clients from disaster — and most standard contracts simply don\'t have them.',
    content: null,
    category: 'events',
    thumbnail_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80',
    published: true,
    created_at: '2024-11-28T10:00:00',
    updated_at: '2024-11-28T10:00:00',
  },
]

export const placeholderSponsorshipInventory: SponsorshipInventory[] = [
  {
    id: '1',
    production_title: 'Neon Nights — Mumbai',
    vertical: 'events',
    tier: 'title',
    price: 500000,
    reach: '5,000 in-venue + 500K social reach',
    spots_total: 1,
    spots_remaining: 1,
    event_id: '1',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    production_title: 'Neon Nights — Mumbai',
    vertical: 'events',
    tier: 'co-sponsor',
    price: 200000,
    reach: '5,000 in-venue + 200K social reach',
    spots_total: 3,
    spots_remaining: 2,
    event_id: '1',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    production_title: 'Rhythm & Roots Festival — Bangalore',
    vertical: 'music',
    tier: 'title',
    price: 750000,
    reach: '8,000 in-venue + 800K social reach',
    spots_total: 1,
    spots_remaining: 1,
    event_id: '2',
    active: true,
    created_at: new Date().toISOString(),
  },
]

export const stats = {
  songsProduced: 340,
  eventsExecuted: 218,
  sponsorsMatched: 127,
  totalReachMillions: 2.4,
}

export const trustLogos = [
  { name: 'Sony Music', logo: null },
  { name: 'Zee Entertainment', logo: null },
  { name: 'Star Sports', logo: null },
  { name: 'PepsiCo India', logo: null },
  { name: 'Spotify India', logo: null },
  { name: 'BookMyShow', logo: null },
  { name: 'Myntra', logo: null },
  { name: 'Apple Music', logo: null },
]
